# -*- coding: utf-8 -*-
"""Dimensionality Reduction Report

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RxUZylmWHkv3CelUU_Xt7F568hOo-Ad2
"""

import pandas as pd
import numpy as np
import seaborn as sns

from sklearn.datasets import load_breast_cancer
data = load_breast_cancer()
df = pd.DataFrame(data=data.data, columns=data.feature_names)
df['target'] = data.target
df.columns = df.columns.str.lower().str.replace(" ", "_")
df.head()

df.describe()

df.shape

# Count each class
class_counts = df['target'].value_counts()

# Convert to percentages
class_percentages = df['target'].value_counts(normalize=True) * 100

# Combine into one table
class_distribution = pd.DataFrame({
    'Count': class_counts,
    'Percentage (%)': class_percentages
})

# Replace labels for readability
class_distribution.index = ['Malignant', 'Benign']

class_distribution

import matplotlib.pyplot as plt

# Get counts
class_counts = df['target'].value_counts()

# Rename for clarity
class_counts.index = ['Malignant', 'Benign']

# Calculate percentages
total = class_counts.sum()
percentages = (class_counts / total) * 100

# Plot
plt.figure(figsize=(6, 4))
bars = plt.bar(class_counts.index, class_counts.values)

# Add labels on top
for i, bar in enumerate(bars):
    plt.text(
        bar.get_x() + bar.get_width() / 2,
        bar.get_height(),
        f"{class_counts[i]} ({percentages[i]:.1f}%)",
        ha='center',
        va='bottom'
    )

# Labels + title
plt.xlabel('Diagnosis')
plt.ylabel('Number of Samples')
plt.title('Target Variable Distribution')

plt.show()

df.isnull().sum().sum()

df.duplicated().sum()

df.dtypes

# Drop target column (we only want features)
features = df.drop(columns=['target'])

# Summary statistics
summary_stats = features.describe().T

summary_stats

features = df.drop(columns=['target'])

# Calculate range
range_values = features.max() - features.min()

# Put into a clean table
range_df = pd.DataFrame({
    'Min': features.min(),
    'Max': features.max(),
    'Range': range_values
})

range_df

# Drop target column
features = df.drop(columns=['target'])

# Calculate variance and sort
variance_sorted = features.var().sort_values(ascending=False)

variance_sorted

import matplotlib.pyplot as plt

# Get counts
class_counts = df['target'].value_counts()

# Rename for clarity
class_counts.index = ['Malignant', 'Benign']

# Calculate percentages
total = class_counts.sum()
percentages = (class_counts / total) * 100

# Plot
plt.figure(figsize=(6, 4))
bars = plt.bar(class_counts.index, class_counts.values)

# Add labels on top
for i, bar in enumerate(bars):
    plt.text(
        bar.get_x() + bar.get_width() / 2,
        bar.get_height(),
        f"{class_counts[i]} ({percentages[i]:.1f}%)",
        ha='center',
        va='bottom'
    )

# Labels + title
plt.xlabel('Diagnosis')
plt.ylabel('Number of Samples')
plt.title('Target Variable Distribution')

plt.show()

import matplotlib.pyplot as plt

features = df.drop(columns=['target'])

# Bigger figure + spacing
fig = features.hist(figsize=(18, 12))

# Adjust spacing between plots
plt.subplots_adjust(hspace=0.6, wspace=0.4)

# Add main title with spacing
plt.suptitle("Feature Distributions", fontsize=16, y=0.97)

plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

# Add readable labels
df['diagnosis'] = df['target'].map({0: 'Malignant', 1: 'Benign'})

selected_features = [
    'mean_radius',
    'mean_perimeter',
    'mean_area',
    'mean_concave_points',
    'worst_radius'
]

# Create subplot grid (3 rows, 2 columns)
fig, axes = plt.subplots(3, 2, figsize=(12, 12))

axes = axes.flatten()  # makes indexing easier

# Plot each feature
for i, feature in enumerate(selected_features):
    sns.boxplot(x='diagnosis', y=feature, data=df, ax=axes[i])
    axes[i].set_title(f"{feature} by Diagnosis")

# Remove the empty subplot (last one)
fig.delaxes(axes[-1])

# Adjust layout
plt.tight_layout()
plt.show()

plt.figure(figsize=(14, 12))

correlation_matrix = df.drop(columns=['target', 'diagnosis']).corr()

sns.heatmap(correlation_matrix, cmap='coolwarm')

plt.title("Correlation Heatmap (30x30 Features)")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

# Make sure diagnosis column exists
df['diagnosis'] = df['target'].map({0: 'Malignant', 1: 'Benign'})

selected_features = [
    'mean_radius',
    'mean_perimeter',
    'mean_area',
    'mean_concave_points',
    'worst_radius'
]

# Pairplot
sns.pairplot(
    df[selected_features + ['diagnosis']],
    hue='diagnosis',
    diag_kind='hist'
)

plt.suptitle("Pairplot of Selected Features by Diagnosis", y=1.02)
plt.show()

import matplotlib.pyplot as plt

# Calculate variance (USE ORIGINAL DATA)
variance = df.drop(columns=['target', 'diagnosis']).var()

# Sort from highest → lowest
variance_sorted = variance.sort_values(ascending=False)

# Plot
plt.figure(figsize=(12, 6))
variance_sorted.plot(kind='bar')

plt.title("Feature Variance Comparison")
plt.xlabel("Features")
plt.ylabel("Variance")
plt.xticks(rotation=90)

plt.show()

features = df.drop(columns=['target', 'diagnosis'])

# Coefficient of Variation
cv = (features.std() / features.mean()).sort_values(ascending=False)

cv

import matplotlib.pyplot as plt

plt.figure(figsize=(12,6))
cv.plot(kind='bar')

plt.title("Relative Variability (Coefficient of Variation)")
plt.xlabel("Features")
plt.ylabel("CV (std / mean)")
plt.xticks(rotation=90)

plt.show()

from sklearn.preprocessing import StandardScaler

features = df.drop(columns=['target', 'diagnosis'])

scaler = StandardScaler()
scaled_features = scaler.fit_transform(features)

scaled_df = pd.DataFrame(scaled_features, columns=features.columns)

scaled_df.head()

print("BEFORE SCALING:")
print(features[['mean_area', 'mean_smoothness']].head())

print("\nAFTER SCALING:")
print(scaled_df[['mean_area', 'mean_smoothness']].head())

print("Mean after scaling:")
print(scaled_df.mean())

print("\nStd after scaling:")
print(scaled_df.std())

import matplotlib.pyplot as plt

selected_features = [
    'mean_radius',
    'mean_perimeter',
    'mean_area',
    'mean_concave_points',
    'worst_radius'
]

# Loop through each feature
for feature in selected_features:
    plt.figure(figsize=(10,4))

    # BEFORE scaling
    plt.subplot(1,2,1)
    plt.hist(df[feature], bins=20)
    plt.title(f"{feature} (Before Scaling)")
    plt.xlabel(feature)
    plt.ylabel("Frequency")

    # AFTER scaling
    plt.subplot(1,2,2)
    plt.hist(scaled_df[feature], bins=20)
    plt.title(f"{feature} (After Scaling)")
    plt.xlabel(feature)

    plt.tight_layout()
    plt.show()

from sklearn.model_selection import train_test_split

# Features and target
X = scaled_df   # use scaled data for modeling
y = df['target']

# 80/20 split with stratification
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

print("Training set size:", X_train.shape[0])
print("Testing set size:", X_test.shape[0])

print("\nOriginal distribution:")
print(y.value_counts(normalize=True))

print("\nTrain distribution:")
print(y_train.value_counts(normalize=True))

print("\nTest distribution:")
print(y_test.value_counts(normalize=True))

"""PCA Usage"""

from sklearn.decomposition import PCA
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Fit PCA on TRAINING data (important)
pca = PCA()
pca.fit(X_train)

explained_variance = pca.explained_variance_ratio_
cumulative_variance = np.cumsum(explained_variance)

plt.figure(figsize=(8,5))
plt.plot(range(1, len(explained_variance)+1), explained_variance, marker='o')
plt.title("Scree Plot")
plt.xlabel("Principal Component")
plt.ylabel("Explained Variance Ratio")
plt.show()

plt.figure(figsize=(8,5))
plt.plot(range(1, len(cumulative_variance)+1), cumulative_variance, marker='o')
plt.axhline(y=0.95, linestyle='--')  # 95% threshold
plt.title("Cumulative Explained Variance")
plt.xlabel("Number of Components")
plt.ylabel("Cumulative Variance")
plt.show()

from sklearn.decomposition import PCA
import pandas as pd
import numpy as np

# Fit PCA on training data
pca = PCA()
pca.fit(X_train)

# Get explained variance for each component
explained_variance = pca.explained_variance_ratio_

# Get cumulative variance
cumulative_variance = np.cumsum(explained_variance)

# Create table
pca_variance_table = pd.DataFrame({
    "Component (k)": range(1, len(explained_variance) + 1),
    "Explained Variance Ratio": explained_variance,
    "Cumulative Variance": cumulative_variance
})

# Display table
pca_variance_table

optimal_k = np.argmax(cumulative_variance >= 0.95) + 1
print("Optimal number of components (95% variance):", optimal_k)

for k in [2, 5, 10, 15]:
    pca_temp = PCA(n_components=k)
    pca_temp.fit(X_train)

    total_var = pca_temp.explained_variance_ratio_.sum()
    print(f"k = {k}: Total Variance = {total_var:.4f}")

pca_optimal = PCA(n_components=10)
pca_optimal.fit(X_train)

X_train_pca = pca_optimal.transform(X_train)
X_test_pca = pca_optimal.transform(X_test)

explained_variance = pca_optimal.explained_variance_ratio_

print("Variance explained by PC1:", explained_variance[0])
print("Variance explained by PC2:", explained_variance[1])

total_variance = explained_variance.sum()
print("Total variance explained by 10 components:", total_variance)

# Use existing PCA results (DO NOT refit)

pca_vis_df = pd.DataFrame(
    X_train_pca[:, :3],
    columns=['PC1', 'PC2', 'PC3']
)

pca_vis_df['target'] = y_train.values
pca_vis_df['diagnosis'] = pca_vis_df['target'].map({0: 'Malignant', 1: 'Benign'})

explained = pca_optimal.explained_variance_ratio_

plt.figure(figsize=(8, 6))

for diagnosis in ['Malignant', 'Benign']:
    subset = pca_vis_df[pca_vis_df['diagnosis'] == diagnosis]
    plt.scatter(subset['PC1'], subset['PC2'], label=diagnosis, alpha=0.7)

plt.xlabel(f"PC1 ({explained[0]*100:.2f}% variance)")
plt.ylabel(f"PC2 ({explained[1]*100:.2f}% variance)")
plt.title("2D PCA Projection: PC1 vs PC2")
plt.legend()

plt.show()

from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt

fig = plt.figure(figsize=(10, 8))
ax = fig.add_subplot(111, projection='3d')

for diagnosis in ['Malignant', 'Benign']:
    subset = pca_vis_df[pca_vis_df['diagnosis'] == diagnosis]
    ax.scatter(
        subset['PC1'],
        subset['PC2'],
        subset['PC3'],
        label=diagnosis,
        alpha=0.7,
        s=50
    )

ax.set_xlabel(f"PC1 ({explained[0]*100:.2f}% variance)")
ax.set_ylabel(f"PC2 ({explained[1]*100:.2f}% variance)")
ax.set_zlabel(f"PC3 ({explained[2]*100:.2f}% variance)")
ax.set_title("3D PCA Graph: PC1 vs PC2 vs PC3")
ax.legend()

plt.show()

# Get loadings (rows = PCs, columns = features)
loadings = pd.DataFrame(
    pca_optimal.components_,
    columns=X_train.columns,
    index=[f'PC{i+1}' for i in range(pca_optimal.n_components_)]
)

loadings

loadings.loc['PC1'].sort_values(ascending=False).head(5)

loadings.loc['PC2'].sort_values(ascending=False).head(5)

for k in [2, 5, 10, 15]:
    pca_temp = PCA(n_components=k)
    pca_temp.fit(X_train)

    total_var = pca_temp.explained_variance_ratio_.sum()
    print(f"k = {k}: Total Variance = {total_var:.4f}")

"""LDA Usage"""

from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

# Initialize LDA (max 1 component for binary classification)
lda = LinearDiscriminantAnalysis(n_components=1)

# Fit on training data
lda.fit(X_train, y_train)

# Transform data
X_train_lda = lda.transform(X_train)
X_test_lda = lda.transform(X_test)

print("Explained variance ratio (LD1):", lda.explained_variance_ratio_)

import matplotlib.pyplot as plt

# Separate classes
malignant = X_train_lda[y_train == 0]
benign = X_train_lda[y_train == 1]

plt.figure(figsize=(8,5))

plt.hist(malignant, bins=30, alpha=0.7, label='Malignant')
plt.hist(benign, bins=30, alpha=0.7, label='Benign')

plt.xlabel("LD1")
plt.ylabel("Frequency")
plt.title("LDA Distribution (LD1) by Class")
plt.legend()

plt.show()

from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

# Initialize LDA (1 component for binary classification)
lda = LinearDiscriminantAnalysis(n_components=1)

# Fit model
lda.fit(X_train, y_train)

# Get explained variance ratio
lda_variance = lda.explained_variance_ratio_

print("Explained Variance Ratio (LD1):", lda_variance)

# Get coefficients
lda_coefficients = pd.Series(
    lda.coef_[0],
    index=X_train.columns
)

# Top 5 features (by magnitude)
top_features = lda_coefficients.abs().sort_values(ascending=False)

top_features

lda_coefficients.sort_values(ascending=False)

"""Comparision Between PCA and LDA"""

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

# -----------------------------
# PCA data for plotting
# -----------------------------
pca_compare_df = pd.DataFrame({
    'PC1': X_train_pca[:, 0],
    'PC2': X_train_pca[:, 1],
    'target': y_train.values
})
pca_compare_df['diagnosis'] = pca_compare_df['target'].map({0: 'Malignant', 1: 'Benign'})

# -----------------------------
# LDA data for plotting
# -----------------------------
lda_compare_df = pd.DataFrame({
    'LD1': X_train_lda[:, 0],
    'target': y_train.values
})
lda_compare_df['diagnosis'] = lda_compare_df['target'].map({0: 'Malignant', 1: 'Benign'})

# Small jitter so LDA points don't overlap too much
np.random.seed(42)
lda_compare_df['y_jitter'] = np.random.normal(0, 0.03, size=len(lda_compare_df))

# Explained variance for PCA axis labels
pca_explained = pca_optimal.explained_variance_ratio_

# -----------------------------
# Side-by-side plots
# -----------------------------
fig, axes = plt.subplots(1, 2, figsize=(14, 6))

# PCA plot
for diagnosis in ['Malignant', 'Benign']:
    subset = pca_compare_df[pca_compare_df['diagnosis'] == diagnosis]
    axes[0].scatter(subset['PC1'], subset['PC2'], label=diagnosis, alpha=0.7)

axes[0].set_xlabel(f"PC1 ({pca_explained[0]*100:.2f}% variance)")
axes[0].set_ylabel(f"PC2 ({pca_explained[1]*100:.2f}% variance)")
axes[0].set_title("PCA Projection (PC1 vs PC2)")
axes[0].legend()

# LDA plot
for diagnosis in ['Malignant', 'Benign']:
    subset = lda_compare_df[lda_compare_df['diagnosis'] == diagnosis]
    axes[1].scatter(subset['LD1'], subset['y_jitter'], label=diagnosis, alpha=0.7)

axes[1].set_xlabel("LD1")
axes[1].set_ylabel("Jittered Position")
axes[1].set_title("LDA Projection (LD1)")
axes[1].legend()

plt.suptitle("Side-by-Side Comparison of PCA and LDA Projections", fontsize=16)
plt.tight_layout()
plt.show()

sns.stripplot(x='LD1', y='diagnosis', data=lda_compare_df)

from sklearn.linear_model import LogisticRegression

# Model for original data
model_original = LogisticRegression(max_iter=1000)
model_original.fit(X_train, y_train)
y_pred_original = model_original.predict(X_test)

# Model for PCA data
model_pca = LogisticRegression(max_iter=1000)
model_pca.fit(X_train_pca, y_train)
y_pred_pca = model_pca.predict(X_test_pca)

# Model for LDA data
model_lda = LogisticRegression(max_iter=1000)
model_lda.fit(X_train_lda, y_train)
y_pred_lda = model_lda.predict(X_test_lda)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

def get_metrics(y_true, y_pred):
    return {
        "Accuracy": accuracy_score(y_true, y_pred),
        "Precision": precision_score(y_true, y_pred),
        "Recall": recall_score(y_true, y_pred),
        "F1-Score": f1_score(y_true, y_pred)
    }

results = pd.DataFrame([
    ["Original (30 features)", *get_metrics(y_test, y_pred_original).values()],
    ["PCA (10 components)", *get_metrics(y_test, y_pred_pca).values()],
    ["LDA (1 component)", *get_metrics(y_test, y_pred_lda).values()]
],
columns=["Model", "Accuracy", "Precision", "Recall", "F1-Score"])

results.round(4)