# -*- coding: utf-8 -*-
"""PCA Notebook

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cQqDkA_EJO1TMb9o0Ws_rgtj7jsf8nW1
"""

import pandas as pd
import numpy as np
import seaborn as sns

#importing the dataset
iris_df = sns.load_dataset("iris")
#print dataset header
iris_df.head()

#creating feature set
X = iris_df.drop( ['species'], axis=1)
#creating label set
y = iris_df["species"]
#converting labels to numbers
from sklearn import preprocessing
le = preprocessing.LabelEncoder( )
y = le.fit_transform(y)

#dividing data into 80-20% traning and test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=0)

#applying scaling on training and test data
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform (X_test)

#importing PCA class
from sklearn.decomposition import PCA
#creating object of the PCA class
pca = PCA()
#training PCA model on training data
X_train = pca.fit_transform(X_train)
#making predictions on test data
X_test = pca.transform(X_test)

#printing variance ratios
variance_ratios = pca.explained_variance_ratio_
print(variance_ratios)

#use two principal components
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

#making predictions using logistic regression
from sklearn.linear_model import LogisticRegression
#training the logistic regression model
lg = LogisticRegression ( )
lg.fit ( X_train , y_train )
# Predicting the Test set results
y_pred = lg.predict ( X_test )
#evaluating results
from sklearn.metrics import accuracy_score
print ( accuracy_score ( y_test , y_pred ) )
# 0.8666666666666667

# Commented out IPython magic to ensure Python compatibility.
from matplotlib import pyplot as plt
# %matplotlib inline
#print actual datapoints
plt.scatter(X_test[:,0], X_test[:,1], c= y_test, cmap='rainbow')

