# -*- coding: utf-8 -*-
"""PCA and LDA Notebook

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bZHdN9LIepVKVk2xFcyfZSPu5DU-q6cN
"""

import pandas as pd
import numpy as np
import seaborn as sns

#importing dataset
banknote_df = pd.read_csv("https://raw.githubusercontent.com/Sanchitbhadani-1/Dimensionality-Reduction/refs/heads/main/Learning%20PCA%20and%20LDA/banknote(in).csv")
#displaying dataset header
banknote_df.head()

# dividing data into features and labels
X = banknote_df.drop(["class"], axis = 1)
y = banknote_df.filter(["class"], axis = 1)

#dividing data into 80-20% training and test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,
test_size=0.20, random_state=0)

#applying scaling on training and test data
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#importing PCA class
from sklearn.decomposition import PCA
#creating object of the PCA class
pca = PCA()
#training PCA model on training data
X_train = pca.fit_transform(X_train)
#making predictions on test data
X_test = pca.transform(X_test)

#printing variance ratios
variance_ratios = pca.explained_variance_ratio_
print(variance_ratios)

#use two principal components
from sklearn.decomposition import PCA
# The 'X_train' data currently has only 1 feature due to the previous PCA step (in cell OWOegn0Vdwpa).
# Therefore, n_components can at most be 1.
# If you intended to have 2 components, you should specify n_components=2 in the initial PCA call.
pca = PCA(n_components=1) # Changed from 2 to 1 to resolve the ValueError
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

#making predictions using logistic regression
from sklearn.linear_model import LogisticRegression
#training the logistic regression model
lg = LogisticRegression ( )
lg.fit ( X_train , y_train )
# Predicting the Test set results
y_pred = lg.predict ( X_test )
#evaluating results
from sklearn.metrics import accuracy_score
print ( accuracy_score ( y_test , y_pred ) )
# 0.8666666666666667

#importing LDA class
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
#creating object of the LDA class
lda = LDA()
#training LDA model on training data
X_train = lda.fit_transform(X_train, y_train)
#making predictions on test data
X_test = lda.transform(X_test)

#printing variance ratios
variance_ratios = lda.explained_variance_ratio_
print(variance_ratios)
# Output: [1.]

#creating object of the LDA class
lda = LDA(n_components = 1)
#training PCA model on training data
X_train = lda.fit_transform(X_train, y_train)
#making predictions on test data
X_test = lda.transform(X_test)

#making predictions using logistic regression
from sklearn.linear_model import LogisticRegression
#training the logistic regression model
lg = LogisticRegression()
lg.fit(X_train, y_train)
# Predicting the Test set results
y_pred = lg.predict(X_test)
#evaluating results
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

churn_df = pd.read_csv("/content/drive/MyDrive/Data/customer_churn(in).csv")
churn_df.head()

churn_df = churn_df.drop(["RowNumber", "CustomerId", "Surname"], axis=1)

X = churn_df.drop(['Exited'], axis=1)
y = churn_df['Exited']

numerical = X.drop(['Geography', 'Gender'], axis = 1)
numerical.head()

categorical = X.filter(['Geography', 'Gender'])
categorical.head()

cat_numerical = pd.get_dummies(categorical,drop_first=True)
cat_numerical.head()

X = pd.concat([numerical, cat_numerical], axis = 1)
X.head()

#dividing data into 80-20% training and test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,
test_size=0.20, random_state=0)

#applying scaling on training and test data
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#importing PCA class
from sklearn.decomposition import PCA
#creating object of the PCA class
pca = PCA()
#training PCA model on training data
X_train = pca.fit_transform(X_train)
#making predictions on test data
X_test = pca.transform(X_test)

#printing variance ratios
variance_ratios = pca.explained_variance_ratio_
print(variance_ratios)

#use two principal components
from sklearn.decomposition import PCA
# The 'X_train' data currently has only 1 feature due to the previous PCA step (in cell OWOegn0Vdwpa).
# Therefore, n_components can at most be 1.
# If you intended to have 2 components, you should specify n_components=2 in the initial PCA call.
pca = PCA(n_components=1) # Changed from 2 to 1 to resolve the ValueError
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

#making predictions using logistic regression
from sklearn.linear_model import LogisticRegression
#training the logistic regression model
lg = LogisticRegression ( )
lg.fit ( X_train , y_train )
# Predicting the Test set results
y_pred = lg.predict ( X_test )
#evaluating results
from sklearn.metrics import accuracy_score
print ( accuracy_score ( y_test , y_pred ) )
# 0.8666666666666667

#importing LDA class
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
#creating object of the LDA class
lda = LDA()
#training LDA model on training data
X_train = lda.fit_transform(X_train, y_train)
#making predictions on test data
X_test = lda.transform(X_test)

#printing variance ratios
variance_ratios = lda.explained_variance_ratio_
print(variance_ratios)
# Output: [1.]

#creating object of the LDA class
lda = LDA(n_components = 1)
#training PCA model on training data
X_train = lda.fit_transform(X_train, y_train)
#making predictions on test data
X_test = lda.transform(X_test)

#making predictions using logistic regression
from sklearn.linear_model import LogisticRegression
#training the logistic regression model
lg = LogisticRegression()
lg.fit(X_train, y_train)
# Predicting the Test set results
y_pred = lg.predict(X_test)
#evaluating results
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)